<?php

/**
 * @Entity("pergunta")
 */
class Pergunta extends Model {

    /**
     * @AutoGenerated()
     * @Column(Type="int",Key="Primary")
     */
    public $Id;

    /**
     * @Column(Type="String")
     */
    public $Texto;

    //método para salvar nova pergunta
    public function save($pergunta) {
        try {
            $db = Database::factory();
            $novaPergunta = new Pergunta();
            $novaPergunta->Texto = $pergunta;
            $db->Pergunta->insert($novaPergunta);
            return($novaPergunta->Id);
        } catch (Exception $e) {
            return("Erro ao criar pergunta: " . $e);
        }
    }

}
