<?php

/**
 * @Entity("resposta")
 */
class Resposta extends Model
{
	/**
	 * @AutoGenerated()
	 * @Column(Type="Int",Key="Primary")
	 */
	public $Id;

	/**
	 * @Column(Type="Int")
	 */
	public $IdResultado;

	/**
	 * @Column(Type="Int")
	 */
	public $IdPergunta;

	/**
	 * @Column(Type="String")
	 */
	public $Resposta;
        
    public function __construct($idResultado, $idPergunta, $resposta) 
    {
        $this->IdPergunta = (int) $idPergunta;
        $this->IdResultado = (int) $idResultado;
        $this->Resposta = $resposta;
    }

	public static function encontrarTodas($idPergunta)
	{
		$db = Database::factory();
		return $db->Resposta->where('IdPergunta = ?', $idPergunta)->all();
	}
}