<?php

/**
 * @Entity("resposta")
 */
class Resposta extends Model
{
	/**
	 * @AutoGenerated()
	 * @Column(Type="Int",Key="Primary")
	 */
	public $Id;

	/**
	 * @Column(Type="Int")
	 */
	public $IdResultado;

	/**
	 * @Column(Type="Int")
	 */
	public $IdPergunta;

	/**
	 * @Column(Type="String")
	 */
	public $Resposta;
}