<?php

/**
 * @Entity("resultado")
 */
class Resultado extends Model
{
	/**
	 * @AutoGenerated()
	 * @Column(Type="Int",Key="Primary")
	 */
	public $Id;

	/**
	 * @Column(Type="String")
	 */
	public $Solucao;

	/**
	 * @Column(Type="String")
	 */
	public $Problema;
        
    public function __construct($problema, $solucao) 
    {
        $this->Problema = $problema;
        $this->Solucao = $solucao;
    }
    
    public static function findAll()
        {
            $db = Database::factory();
            return $db->Problema->all();
        }
}