<?php

/**
 * @Entity("resultado")
 */
class Resultado extends Model
{
	/**
	 * @AutoGenerated()
	 * @Column(Type="Int",Key="Primary")
	 */
	public $Id;

	/**
	 * @Column(Type="String")
	 */
	public $Solucao;

	/**
	 * @Column(Type="String")
	 */
	public $Problema;
}