<?php

/**
 * @Entity("usuario")
 */
class Usuario extends Model
{

	/**
	 * @AutoGenerated()
	 * @Column(Type="Int",Key="Primary")
	 */
	public $Id;

	/**
	 * @Column(Type="String")
	 * @Required()
	 */
	public $Login;

	/**
	 * @Column(Type="String")
	 * @Required()
	 */
	public $Senha;

	/**
	 * @Column(Type="String")
	 */
	public $Nome;
	
}