<?php

/**
 * @Entity("usuario")
 */
class Usuario extends Model
{

	/**
	 * @AutoGenerated()
	 * @Column(Type="Int",Key="Primary")
	 */
	public $Id;

	/**
	 * @Column(Type="String")
	 * @Required()
	 */
	public $Login;

	/**
	 * @Column(Type="String")
	 * @Required()
	 */
	public $Senha;

	/**
	 * @Column(Type="String")
	 */
	public $Nome;	
        
        public static function login($login, $password) {
        try {
            $db = Database::getInstance();
            $user = $db->Usuario->single('Login = ? AND Senha = ?', $login, $password);
            return $user;
        } catch (Exception $e) {
            exit("Erro ao logar: " . $e);
        }
    }
}